name: Publish package to the Maven Central Repository
on:
  pull_request:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - id: install-secret-key
        name: Install GPG secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - id: build-and-publish
        name: Publish package
        run: ./gradlew build --stacktrace \
          -Prelease=publish \
          -PsigningKeyId=${{ secrets.GPG_KEY_ID }} \
          -PsigningKey=${{ secrets.GPG_PRIVATE_KEY }} \
          -PsigningPassword=${{ secrets.GPG_PASSPHRASE }}
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
